# wrangler.toml
# The name of your project. This will be part of the final URL.
name = "tech-flow"

# The date of the Workers runtime version to use.
compatibility_date = "2024-06-24"

# This tells Wrangler where your final build folder is.
main = "dist/index.js"                 # Path to your Worker script
type = "javascript"                    # Or "module" if using ESModules
workers_dev = true                     # Deploy to workers.dev subdomain